FIX: Fix missing boost::nowide::declaration
/run/build/BambuStudio/src/slic3r/GUI/GCodeRenderer/AdvancedRenderer.cpp:357: error: ‘fopen’ is not a member of ‘boost::nowide’
  357 |                 fp = boost::nowide::fopen(filename, "w");