slic3r: Fix missing boost::lexical_cast declaration
src/slic3r/GUI/MediaFilePanel.cpp: In lambda function:
src/slic3r/GUI/MediaFilePanel.cpp:508:49: error: ‘lexical_cast’ is not a member of ‘boost’
  508 |                 url += "&refresh_url=" + boost::lexical_cast<std::string>(&refresh_agora_url);
      |                                                 ^~~~~~~~~~~~