FIX: Fix missing union_ex/offset_ex declaration
/run/build/BambuStudio/src/libslic3r/Interlocking/InterlockingGenerator.cpp: In member function ‘std::pair<std::vector<Slic3r::ExPolygon>, std::vector<Slic3r::ExPolygon> > Slic3r::InterlockingGenerator::growBorderAreasPerpendicular(const Slic3r::ExPolygons&, const Slic3r::ExPolygons&, const coord_t&) const’:
/run/build/BambuStudio/src/libslic3r/Interlocking/InterlockingGenerator.cpp:70:56: error: ‘offset_ex’ was not declared in this scope; did you mean ‘offsetof’?
   70 |     const ExPolygons total_shrunk = offset_ex(union_ex(offset_ex(a, min_line), offset_ex(b, min_line)), 2 * -min_line);
      |                                                        ^~~~~~~~~
      |                                                        offsetof
/run/build/BambuStudio/src/libslic3r/Interlocking/InterlockingGenerator.cpp:70:47: error: ‘union_ex’ was not declared in this scope; did you mean ‘union’?
   70 |     const ExPolygons total_shrunk = offset_ex(union_ex(offset_ex(a, min_line), offset_ex(b, min_line)), 2 * -min_line);
      |                                               ^~~~~~~~
      |                                               union