slic3r: Fix missing union_ex/diff_ex declaration
src/slic3r/GUI/Gizmos/GLGizmoBrimEars.cpp: In member function ‘void Slic3r::GUI::GLGizmoBrimEars::first_layer_slicer()’:
src/slic3r/GUI/Gizmos/GLGizmoBrimEars.cpp:870:27: error: ‘union_ex’ was not declared in this scope; did you mean ‘union’?
  870 |                 part_ex = union_ex(part_ex, sliced_layer);
      |                           ^~~~~~~~
      |                           union
src/slic3r/GUI/Gizmos/GLGizmoBrimEars.cpp:876:21: error: ‘diff_ex’ was not declared in this scope
  876 |     m_first_layer = diff_ex(part_ex, negative_ex);
      |                     ^~~~~~~