FIX: Fix missing diff/diff_ex/etc. declarations
/run/build/BambuStudio/src/libslic3r/GCode/TimelapsePosPicker.cpp: In member function ‘void Slic3r::TimelapsePosPicker::construct_printable_area_by_printer()’:
/run/build/BambuStudio/src/libslic3r/GCode/TimelapsePosPicker.cpp:102:49: error: ‘diff’ was not declared in this scope
  102 |             ExPolygons printable_area = diff_ex(diff(m_bed_polygon, bed_exclude_area), { wipe_tower_area });
      |                                                 ^~~~
/run/build/BambuStudio/src/libslic3r/GCode/TimelapsePosPicker.cpp:102:41: error: ‘diff_ex’ was not declared in this scope
  102 |             ExPolygons printable_area = diff_ex(diff(m_bed_polygon, bed_exclude_area), { wipe_tower_area });
      |                                         ^~~~~~~
/run/build/BambuStudio/src/libslic3r/GCode/TimelapsePosPicker.cpp:107:34: error: ‘intersection_ex’ was not declared in this scope
  107 |                 printable_area = intersection_ex(printable_area, Polygons{ extruder_printable_area });
      |                                  ^~~~~~~~~~~~~~~
/run/build/BambuStudio/src/libslic3r/GCode/TimelapsePosPicker.cpp: In member function ‘Slic3r::ExPolygons Slic3r::TimelapsePosPicker::collect_object_slices_data(const Slic3r::Layer*, float, const std::vector<const Slic3r::PrintObject*>&, bool)’:
/run/build/BambuStudio/src/libslic3r/GCode/TimelapsePosPicker.cpp:154:15: error: ‘union_ex’ was not declared in this scope; did you mean ‘union’?
  154 |         ret = union_ex(ret);
      |               ^~~~~~~~
      |               union
/run/build/BambuStudio/src/libslic3r/GCode/TimelapsePosPicker.cpp:132:15: warning: unused variable ‘z_target’ [-Wunused-variable]
  132 |         float z_target = layer->print_z;
      |               ^~~~~~~~
/run/build/BambuStudio/src/libslic3r/GCode/TimelapsePosPicker.cpp: In member function ‘Slic3r::Polygons Slic3r::TimelapsePosPicker::collect_limit_areas_for_camera(const std::vector<const Slic3r::PrintObject*>&)’:
/run/build/BambuStudio/src/libslic3r/GCode/TimelapsePosPicker.cpp:164:15: error: ‘union_’ was not declared in this scope; did you mean ‘union’?
  164 |         ret = union_(ret);
      |               ^~~~~~
      |               union
/run/build/BambuStudio/src/libslic3r/GCode/TimelapsePosPicker.cpp: In member function ‘Slic3r::Polygon Slic3r::TimelapsePosPicker::expand_object_projection(const Slic3r::Polygon&, bool)’:
/run/build/BambuStudio/src/libslic3r/GCode/TimelapsePosPicker.cpp:260:20: error: ‘offset’ was not declared in this scope; did you mean ‘off_t’?
  260 |         auto ret = offset(poly, radius);
      |                    ^~~~~~
      |                    off_t
/run/build/BambuStudio/src/libslic3r/GCode/TimelapsePosPicker.cpp: In function ‘Slic3r::Point Slic3r::pick_pos_internal(const Point&, const ExPolygons&, const ExPolygons&, bool)’:
/run/build/BambuStudio/src/libslic3r/GCode/TimelapsePosPicker.cpp:406:17: error: ‘intersection_pl’ was not declared in this scope
  406 |             if (intersection_pl(path, path_collision_area).empty())
      |                 ^~~~~~~~~~~~~~~
/run/build/BambuStudio/src/libslic3r/GCode/TimelapsePosPicker.cpp:376:16: warning: unused variable ‘min_distance’ [-Wunused-variable]
  376 |         double min_distance = std::numeric_limits<double>::max();
      |                ^~~~~~~~~~~~
/run/build/BambuStudio/src/libslic3r/GCode/TimelapsePosPicker.cpp: In member function ‘Slic3r::Point Slic3r::TimelapsePosPicker::pick_pos_for_curr_layer(const Slic3r::PosPickCtx&)’:
/run/build/BambuStudio/src/libslic3r/GCode/TimelapsePosPicker.cpp:474:47: error: ‘union_ex’ was not declared in this scope; did you mean ‘union’?
  474 |         ExPolygons unplacable_area = union_ex(union_ex(layer_slices, camera_limit_areas), rod_limit_areas);
      |                                               ^~~~~~~~
      |                                               union
/run/build/BambuStudio/src/libslic3r/GCode/TimelapsePosPicker.cpp:474:38: error: ‘union_ex’ was not declared in this scope; did you mean ‘union’?
  474 |         ExPolygons unplacable_area = union_ex(union_ex(layer_slices, camera_limit_areas), rod_limit_areas);
      |                                      ^~~~~~~~
      |                                      union
/run/build/BambuStudio/src/libslic3r/GCode/TimelapsePosPicker.cpp:477:32: error: ‘diff_ex’ was not declared in this scope
  477 |         ExPolygons safe_area = diff_ex(extruder_printable_area, unplacable_area);
      |                                ^~~~~~~
/run/build/BambuStudio/src/libslic3r/GCode/TimelapsePosPicker.cpp:478:21: error: ‘opening_ex’ was not declared in this scope
  478 |         safe_area = opening_ex(safe_area, scale_(FILTER_THRESHOLD));
      |                     ^~~~~~~~~~
/run/build/BambuStudio/src/libslic3r/GCode/TimelapsePosPicker.cpp: In member function ‘Slic3r::Point Slic3r::TimelapsePosPicker::pick_pos_for_all_layer(const Slic3r::PosPickCtx&)’:
/run/build/BambuStudio/src/libslic3r/GCode/TimelapsePosPicker.cpp:564:30: error: ‘union_’ was not declared in this scope; did you mean ‘union’?
  564 |         object_projections = union_(object_projections);
      |                              ^~~~~~
      |                              union
/run/build/BambuStudio/src/libslic3r/GCode/TimelapsePosPicker.cpp:570:39: error: ‘intersection_ex’ was not declared in this scope
  570 |             extruder_printable_area = intersection_ex(m_extruder_printable_area[0], m_extruder_printable_area[1]);
      |                                       ^~~~~~~~~~~~~~~
/run/build/BambuStudio/src/libslic3r/GCode/TimelapsePosPicker.cpp:574:32: error: ‘diff_ex’ was not declared in this scope
  574 |         ExPolygons safe_area = diff_ex(extruder_printable_area, unplacable_area);
      |                                ^~~~~~~
/run/build/BambuStudio/src/libslic3r/GCode/TimelapsePosPicker.cpp:575:21: error: ‘opening_ex’ was not declared in this scope
  575 |         safe_area = opening_ex(safe_area, scale_(FILTER_THRESHOLD));
      |                     ^~~~~~~~~~