FIX: Fix missing wxDC declaration
/run/build/BambuStudio/src/slic3r/Utils/WxFontUtils.hpp: At global scope:
/run/build/BambuStudio/src/slic3r/Utils/WxFontUtils.hpp:44:56: error: ‘wxDC’ has not been declared
   44 |     static void get_suitable_font_size(int max_height, wxDC &dc);
      |                                                        ^~~~