FIX: Fix missing fmod declaration
/run/build/BambuStudio/src/slic3r/GUI/EncodedFilament.hpp: In function ‘Slic3r::ColourHSV Slic3r::wxColourToHSV(const wxColour&)’:
/run/build/BambuStudio/src/slic3r/GUI/EncodedFilament.hpp:41:25: error: ‘fmod’ was not declared in this scope
   41 |             h = 60.0 * (fmod(((g - b) / delta), 6.0));
      |                         ^~~~