FIX: Fix missing stringstream declaration
In file included from /run/build/BambuStudio/src/slic3r/Utils/CertificateVerify.cpp:1:
/run/build/BambuStudio/src/slic3r/Utils/CertificateVerify.hpp: In member function ‘std::string Slic3r::SignerSummary::as_print() const’:
/run/build/BambuStudio/src/slic3r/Utils/CertificateVerify.hpp:25:31: error: aggregate ‘std::stringstream ss’ has incomplete type and cannot be defined
   25 |             std::stringstream ss;
      |                               ^~