FIX: Fix missing union_ declaration
/run/build/BambuStudio/src/slic3r/GUI/Jobs/EmbossJob.cpp:1544: error: ‘union_’ was not declared in this scope; did you mean ‘union’?
 1544 |     Polygons polys = union_(temp_polys);