Fix missing BOOST_LOG_TRIVIAL declaration
/run/build/BambuStudio/src/libslic3r/Brim.cpp: In function ‘void Slic3r::make_brim(const Print&, PrintTryCancel, Polygons&, std::map<ObjectID, ExtrusionEntityCollection>&, std::map<ObjectID, ExtrusionEntityCollection>&, std::vector<std::pair<ObjectID, unsigned int> >&, std::vector<unsigned int>&)’:
/run/build/BambuStudio/src/libslic3r/Brim.cpp:1656:23: error: ‘debug’ was not declared in this scope
 1656 |     BOOST_LOG_TRIVIAL(debug) << "brim_width_max, num_loops: " << brim_width_max << ", " << num_loops;
      |                       ^~~~~
/run/build/BambuStudio/src/libslic3r/Brim.cpp:1656:5: error: ‘BOOST_LOG_TRIVIAL’ was not declared in this scope
 1656 |     BOOST_LOG_TRIVIAL(debug) << "brim_width_max, num_loops: " << brim_width_max << ", " << num_loops;
      |     ^~~~~~~~~~~~~~~~~
/run/build/BambuStudio/src/libslic3r/Brim.cpp: In function ‘Slic3r::ExtrusionEntityCollection Slic3r::make_brim(const Print&, PrintTryCancel, Polygons&)’:
/run/build/BambuStudio/src/libslic3r/Brim.cpp:1675:23: error: ‘debug’ was not declared in this scope
 1675 |     BOOST_LOG_TRIVIAL(debug) << "brim_width_max, num_loops: " << brim_width_max << ", " << num_loops;
      |                       ^~~~~
/run/build/BambuStudio/src/libslic3r/Brim.cpp:1675:5: error: ‘BOOST_LOG_TRIVIAL’ was not declared in this scope
 1675 |     BOOST_LOG_TRIVIAL(debug) << "brim_width_max, num_loops: " << brim_width_max << ", " << num_loops;
      |     ^~~~~~~~~~~~~~~~~