FIX: Fix missing offset() helper declaration
/run/build/BambuStudio/src/libslic3r/GCode/WipeTower.cpp:3327:26: error: ‘offset’ was not declared in this scope; did you mean ‘off_t’?
 3327 |             outer_wall = offset(outer_wall, scaled(spacing)).front();
      |                          ^~~~~~
      |                          off_t