FIX: Fix missing Slic3r::format declaration
/run/build/BambuStudio/src/libslic3r/Fill/FillFloatingConcentric.cpp: In lambda function:
/run/build/BambuStudio/src/libslic3r/Fill/FillFloatingConcentric.cpp:430:49: error: ‘format’ is not a member of ‘Slic3r’; did you mean ‘boost::format’?
  430 |             BOOST_LOG_TRIVIAL(error) << Slic3r::format("ZFiller: both point in subject : %d, %d, %d, %d ", e1_a.z(), e1_b.z(), e2_a.z(), e2_b.z());
      |                                                 ^~~~~~